"""metrics

Revision ID: 6ecc9173dbb5
Revises: 
Create Date: 2025-08-04 15:38:26.612495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ecc9173dbb5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_points',
    sa.Column('dataset_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('decay_value', sa.Float(), nullable=True),
    sa.Column('items_flagged', sa.Integer(), nullable=True),
    sa.Column('notification_type', sa.String(), nullable=True),
    sa.Column('notification_category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('dataset_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_points')
    # ### end Alembic commands ###
