"""add core entities

Revision ID: 84787d5dbf48
Revises: 6ecc9173dbb5
Create Date: 2025-08-06 12:29:32.428241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84787d5dbf48'
down_revision: Union[str, Sequence[str], None] = '6ecc9173dbb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('view_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('element_id', sa.String(), nullable=True),
    sa.Column('breakpoint', sa.String(), nullable=True),
    sa.Column('x', sa.Integer(), nullable=True),
    sa.Column('y', sa.Integer(), nullable=True),
    sa.Column('w', sa.Integer(), nullable=True),
    sa.Column('h', sa.Integer(), nullable=True),
    sa.Column('static', sa.Boolean(), nullable=True),
    sa.Column('dataset_config_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dataset_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('statement_id', sa.String(), nullable=True),
    sa.Column('is_mutable', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sql_statements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('statement', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sql_statements')
    op.drop_table('dataset_configs')
    op.drop_table('view_configs')
    # ### end Alembic commands ###
